import type { FinancialDataConnector } from "./tipos";

/**
 * Catálogo de fuentes externas. Ninguna tiene API oficial ni convenio real
 * hoy (hackathon): cada una es un guion simulado (ver `guiones.ts`) con
 * datos de fixture, igual que la cuenta semilla del proyecto ya usa datos
 * ficticios. Agregar una fuente nueva es agregar una entrada acá — no hace
 * falta tocar el orquestador ni la UI de progreso.
 */
export const CATALOGO_FUENTES: FinancialDataConnector[] = [
  {
    id: "datacredito",
    nombre: "DataCrédito Experian",
    categoria: "credito",
    descripcion: "Score crediticio, obligaciones y bancos activos.",
    escenarioCuenta: "cuenta_existente_login_directo",
    camposAdicionalesRequeridos: [],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: false,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: true,
    otpAutoDetectable: true,
    resultado: {
      tipo: "completed",
      resumen: "Reporte crediticio encontrado.",
      hallazgos: [
        {
          tipo: "credit_report",
          periodo: "2026-08",
          confianza: 0.95,
          datos: { score: 712, obligaciones_activas: 3, entidad: "DataCrédito Experian" },
        },
      ],
    },
  },
  {
    id: "transunion",
    nombre: "TransUnion",
    categoria: "credito",
    descripcion: "Segundo reporte de comportamiento crediticio.",
    escenarioCuenta: "sin_cuenta",
    camposAdicionalesRequeridos: [],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: true,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: false,
    otpAutoDetectable: true,
    resultado: {
      tipo: "completed",
      resumen: "Reporte crediticio encontrado.",
      hallazgos: [
        {
          tipo: "credit_report",
          periodo: "2026-08",
          confianza: 0.9,
          datos: { score: 698, obligaciones_activas: 2, entidad: "TransUnion" },
        },
      ],
    },
  },
  {
    id: "dian",
    nombre: "DIAN",
    categoria: "tributario",
    descripcion: "RUT, información exógena y declaración de renta.",
    escenarioCuenta: "sin_cuenta",
    camposAdicionalesRequeridos: [
      {
        clave: "actividad_economica",
        etiqueta: "Actividad económica principal (código CIIU o descripción)",
      },
    ],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: true,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: false,
    otpAutoDetectable: false,
    resultado: {
      tipo: "completed",
      resumen: "RUT e información exógena encontrados.",
      hallazgos: [
        {
          tipo: "tax_profile",
          periodo: "2025",
          confianza: 0.92,
          datos: { responsabilidades: ["Declarante de renta"], obligaciones_pendientes: 0 },
        },
        {
          tipo: "income",
          periodo: "2025",
          confianza: 0.85,
          datos: { concepto: "Ingreso declarado (exógena)", valor_anual: 72_000_000 },
        },
      ],
    },
  },
  {
    id: "colpensiones",
    nombre: "Colpensiones",
    categoria: "pension",
    descripcion: "Historia laboral y semanas cotizadas en el régimen público.",
    escenarioCuenta: "cuenta_existente_recuperar_clave",
    camposAdicionalesRequeridos: [],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: false,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: false,
    otpAutoDetectable: true,
    resultado: { tipo: "completed_no_data", resumen: "No encontramos historia laboral disponible." },
  },
  {
    id: "porvenir",
    nombre: "Porvenir",
    categoria: "pension",
    descripcion: "Aportes y semanas cotizadas en el régimen privado.",
    escenarioCuenta: "sin_cuenta",
    camposAdicionalesRequeridos: [],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: false,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: false,
    otpAutoDetectable: true,
    resultado: {
      tipo: "completed",
      resumen: "Historia de aportes encontrada.",
      hallazgos: [
        {
          tipo: "pension",
          periodo: "2026-08",
          confianza: 0.88,
          datos: { fondo: "Porvenir", semanas_cotizadas: 312, saldo_cuenta: 18_400_000 },
        },
      ],
    },
  },
  {
    id: "proteccion",
    nombre: "Protección",
    categoria: "pension",
    descripcion: "Aportes y semanas cotizadas en el régimen privado.",
    escenarioCuenta: "cuenta_existente_login_directo",
    camposAdicionalesRequeridos: [],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: false,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: false,
    otpAutoDetectable: true,
    resultado: { tipo: "completed_no_data", resumen: "No encontramos aportes registrados." },
  },
  {
    id: "colfondos",
    nombre: "Colfondos",
    categoria: "pension",
    descripcion: "Aportes y semanas cotizadas en el régimen privado.",
    escenarioCuenta: "sin_cuenta",
    camposAdicionalesRequeridos: [],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: false,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: false,
    otpAutoDetectable: true,
    resultado: { tipo: "completed_no_data", resumen: "No encontramos aportes registrados." },
  },
  {
    id: "skandia",
    nombre: "Skandia",
    categoria: "pension",
    descripcion: "Aportes y semanas cotizadas en el régimen privado.",
    escenarioCuenta: "sin_cuenta",
    camposAdicionalesRequeridos: [],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: false,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: false,
    otpAutoDetectable: true,
    resultado: { tipo: "completed_no_data", resumen: "No encontramos aportes registrados." },
  },
  {
    id: "mi_seguridad_social",
    nombre: "Mi Seguridad Social",
    categoria: "salud",
    descripcion: "Afiliación vigente a salud, pensión y ARL.",
    escenarioCuenta: "cuenta_existente_recuperar_clave",
    camposAdicionalesRequeridos: [],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: false,
    requiereCaptchaRecuperacion: true,
    requiereCaptchaLoginDirecto: false,
    otpAutoDetectable: true,
    resultado: { tipo: "completed_no_data", resumen: "No encontramos novedades pendientes." },
  },
  {
    id: "runt",
    nombre: "RUNT",
    categoria: "vehiculos",
    descripcion: "Vehículos registrados a tu nombre.",
    escenarioCuenta: "cuenta_existente_login_directo",
    camposAdicionalesRequeridos: [],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: false,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: true,
    otpAutoDetectable: true,
    resultado: {
      tipo: "completed",
      resumen: "Un vehículo encontrado.",
      hallazgos: [
        {
          tipo: "vehicle",
          confianza: 0.9,
          datos: { placa: "ABC123", tipo: "Automóvil", modelo: 2019, valor_estimado: 45_000_000 },
        },
      ],
    },
  },
  {
    id: "notariado_vur",
    nombre: "Superintendencia de Notariado y Registro (VUR)",
    categoria: "propiedades",
    descripcion: "Inmuebles registrados a tu nombre.",
    escenarioCuenta: "sin_cuenta",
    camposAdicionalesRequeridos: [
      {
        clave: "matricula_inmobiliaria",
        etiqueta: "Número de matrícula inmobiliaria (opcional, si lo conoces)",
      },
    ],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: false,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: false,
    otpAutoDetectable: true,
    resultado: {
      tipo: "completed",
      resumen: "Un inmueble encontrado.",
      hallazgos: [
        {
          tipo: "property",
          confianza: 0.8,
          datos: { tipo: "Apartamento", ciudad: "Bogotá", valor_catastral: 210_000_000 },
        },
      ],
    },
  },
  {
    id: "simit",
    nombre: "SIMIT",
    categoria: "legal",
    descripcion: "Multas y comparendos de tránsito.",
    escenarioCuenta: "cuenta_existente_login_directo",
    camposAdicionalesRequeridos: [],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: false,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: false,
    otpAutoDetectable: true,
    resultado: { tipo: "completed_no_data", resumen: "No encontramos multas asociadas." },
  },
  {
    id: "rues",
    nombre: "RUES",
    categoria: "empresarial",
    descripcion: "Empresas registradas a tu nombre.",
    escenarioCuenta: "sin_cuenta",
    camposAdicionalesRequeridos: [],
    requiereCaptchaRegistro: false,
    requiereOtpRegistro: false,
    requiereCaptchaRecuperacion: false,
    requiereCaptchaLoginDirecto: false,
    otpAutoDetectable: true,
    resultado: { tipo: "completed_no_data", resumen: "No encontramos empresas asociadas." },
  },
];

export function obtenerFuente(fuenteId: string): FinancialDataConnector | undefined {
  return CATALOGO_FUENTES.find((f) => f.id === fuenteId);
}
